#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-screenshot
Version  : 3.22.0
Release  : 3
URL      : https://download.gnome.org/sources/gnome-screenshot/3.22/gnome-screenshot-3.22.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-screenshot/3.22/gnome-screenshot-3.22.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gnome-screenshot-bin
Requires: gnome-screenshot-data
Requires: gnome-screenshot-locales
Requires: gnome-screenshot-doc
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libcanberra-gtk3)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)

%description
No detailed description available

%package bin
Summary: bin components for the gnome-screenshot package.
Group: Binaries
Requires: gnome-screenshot-data

%description bin
bin components for the gnome-screenshot package.


%package data
Summary: data components for the gnome-screenshot package.
Group: Data

%description data
data components for the gnome-screenshot package.


%package doc
Summary: doc components for the gnome-screenshot package.
Group: Documentation

%description doc
doc components for the gnome-screenshot package.


%package locales
Summary: locales components for the gnome-screenshot package.
Group: Default

%description locales
locales components for the gnome-screenshot package.


%prep
%setup -q -n gnome-screenshot-3.22.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1500836473
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1500836473
rm -rf %{buildroot}
%make_install
%find_lang gnome-screenshot

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-screenshot

%files data
%defattr(-,root,root,-)
/usr/share/GConf/gsettings/gnome-screenshot.convert
/usr/share/appdata/org.gnome.Screenshot.appdata.xml
/usr/share/applications/org.gnome.Screenshot.desktop
/usr/share/dbus-1/services/org.gnome.Screenshot.service
/usr/share/glib-2.0/schemas/org.gnome.gnome-screenshot.gschema.xml

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files locales -f gnome-screenshot.lang
%defattr(-,root,root,-)

